server:
  port: 8081
spring:
  application:
    name: comment
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///redis?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: "123456"
  redis:
    host: 47.120.37.50
    port: 6379
    password: "123456"
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
        max-wait: 1000ms
    database: 3 #选择redis数据库序号
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.linyun.comment.entity # 别名扫描包
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    com.linyun.comment: info
  pattern:
    dateformat: mm:ss.SSS